src_vocab: 'vocabs/EURO/vocab.en.30000'
dst_vocab: 'vocabs/EURO/vocab.de.30000'
src_vocab_size: 16525
dst_vocab_size: 25439
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 1
num_heads: 8
binding_embedding: False
train:
    devices: '3'
    src_path: 'EN-DE-Europarl7/test/concatenated_en2de_test_en.tok.30000'
    # src_path: 'EN-DE-Europarl7/test_trunc/51-55/trunc_test.en'
    out_path: 'EN-DE-Europarl7/test/output.txt'
    tokens_per_batch:  5000
    max_length: 50
    num_epochs: 1
    logdir: './pretrain/model_generator_fren'
    save_freq: 100
    summary_freq: 100
    grads_clip: 5.0
    optimizer: 'adam_decay'
    learning_rate: 0.0001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 1
    shared_embedding: False
