src_vocab: '/home/ming/code/ijcnn/aspec/prepro/ja.vocab'
dst_vocab: '/home/ming/code/ijcnn/aspec/prepro/zh.vocab'
src_vocab_size: 16525
dst_vocab_size: 25439
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 1
num_heads: 8
binding_embedding: False
train:
    devices: '1,2'
    src_path: '/home/ming/code/ijcnn/aspec/raw1/test.tc.norm.tok.ja'
    dst_path: '/home/ming/code/ijcnn/aspec/raw1/test.tc.norm.tok.zh'
    tokens_per_batch:  2500
    max_length: 50
    num_epochs: 60
    logdir: '/home/ming/code/ijcnn/aspec/prepro'
    save_freq: 10
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.0001
    learning_rate_warmup_steps: 4000
    shared_embedding: False
    label_smoothing: 0.1
    batch_size: 2
test:
    src_path: '/home/ming/code/ijcnn/aspec/raw1/test.tc.norm.tok.ja'
    dst_path: '/home/ming/code/ijcnn/aspec/raw1/test.tc.norm.tok.zh'
    # ori_dst_path: './EN-DE-Europarl7/dev/dev.de'
    output_path: '/home/ming/code/ijcnn/aspec/prepro/dev.output'
    batch_size: 1
    max_target_length: 200
    beam_size: 4
    lp_alpha: 0.6
    devices: '0,1'
